name: Create and Upload Release Zip

on:
  push:
    tags:
      - 'v*'  # Match tags that follow the pattern 'v*', e.g., v1.0.0
    branches:
      - 'main'  # Only trigger for tags pushed to the 'main' branch

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Zip files
        run: |
          zip -r release.zip src_test  # Replace 'folder_name' with the actual folder to zip
          ls -lh release.zip  # Check the size of the zip file

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.ref_name }}  # Use the tag name that triggered the workflow
          release_name: Release ${{ github.ref_name }}
          body: |
            This is an automated release.
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Asset
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: release.zip
          asset_name: release.zip
          asset_content_type: application/zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
