name: Zip Files on Push

on:
  push:
    branches:
      - main

jobs:
  zip-files:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # Step 2: Create a ZIP file of all files in /src
    - name: Zip repository contents
      run: |
        zip -r lc-tracker_deployment.zip src_test

    # Step 3: Upload the ZIP file as an artifact (optional)
    - name: Upload ZIP file
      uses: actions/upload-artifact@v3
      with:
        name: src-directory-zip
        path: lc-tracker_deployment.zip
